apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-to-s3
spec:
  schedule: "0 20 * * *"  # daily at 20:00
  timeZone: Europe/Paris
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: api-to-s3
              image: api-to-s3:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: FT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: secret-ft
                      key: FT_CLIENT_ID

                - name: FT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: secret-ft
                      key: FT_CLIENT_SECRET

                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_ACCESS_KEY_ID

                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_SECRET_ACCESS_KEY

                - name: AWS_S3_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: aws-secret
                      key: AWS_S3_BUCKET_NAME
