apiVersion: v1
kind: Service
metadata:
  name: cvee-ui-service
  namespace: cvee
spec:
  type: NodePort
  selector:
    app: cvee-ui
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30081   
