services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cvee_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cvee-api:
    build: ../api
    container_name: cvee-api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: cvee_db
      EMBEDDING_API_URL: http://embedding-service:8001/embed
    depends_on:
      -postgres
        

volumes:
  postgres_data: